# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 赵鑫的技术专栏
brief-intro: Machine learning and algorithms
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://neuzhaoxin.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
twitter_username: #
facebook_username: #
github_username: neuzhaoxin
email: 1677809044@qq.com
weibo_username: 额呃呃呃额呃呃
zhihu_username: #
linkedIn_username: #
dribbble_username:

description_footer: 赵鑫的个人专栏！


# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 short_name
duoshuo_shortname: #hygblog
disqus_shortname: #disqus_9FkQMMr9sz 

gitalk:
    enable: true    #是否开启Gitalk评论
    clientID: 87295a81d7bb4c28c46c                          #生成的clientID
    clientSecret: 21672ad41ae86f5f04cf03a1338f3be2c21b0d4c    #生成的clientSecret
    repo: neuzhaoxin.github.io    #仓库名称
    owner: neuzhaoxin    #github用户名
    admin: neuzhaoxin
    distractionFreeMode: true #是否启用类似FB的阴影遮罩

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
baidu_tongji_id: c73afa66b1c045da55f0321ea721e967
google_analytics_id: #UA-72449510-4 # google 分析追踪id

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
plugins: [jekyll-paginate]
paginate: 6
port: 4001
